Upgrading to antd4
kube-HPC/simulator pull request #176
Opened 2021-09-01 07:45 UTC by zivglik

2021-10-31 09:27 UTC, zivglik commented
/deploy dev1

2021-11-10 13:51 UTC, zivglik commented
/deploy dev1

2021-11-10 14:11 UTC, zivglik commented
/deploy dev1

2021-11-18 10:32 UTC, maty21 commented
/deploy dev1

2021-11-18 11:58 UTC, zivglik commented
/deploy dev1

2021-11-18 13:07 UTC, zivglik commented
/deploy dev1

2021-11-25 12:51 UTC, zivglik commented
/deploy dev1

2021-11-25 13:33 UTC, zivglik commented
/deploy dev1

2021-12-26 08:09 UTC, zivglik commented
/deploy dev1

2021-12-26 09:11 UTC, maty21 commented
___
*[src/components/StatusTag.js, line 29 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-Mrq-KgZBwx8a9lzzKBu:-Mrq-KgZBwx8a9lzzKBv:b-fch136) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/components/StatusTag.js#L29)):*
> ```JavaScript
>       title={tooltip || (status && toUpperCaseFirstLetter(status))}>
>       <Tag
>         color={isDarkMode ? '' : color}
> ```

use theme provider with the following guidelines
 https://css-tricks.com/theming-and-theme-switching-with-react-and-styled-components/


<!-- Sent from Reviewable.io -->

2021-12-26 09:11 UTC, maty21 commented
___
*[src/components/StatusTag.js, line 16 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-Mrpxs3jA2S8cxYtpCcY:-Mrpxs3k1fHqcgL_A392:b1v8ow1) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/components/StatusTag.js#L16)):*
> ```JavaScript
>   style,
> }) => {
>   const { isDarkMode } = useSiteDarkMode();
> ```

why using this hook u call reusable createStore each time 


<!-- Sent from Reviewable.io -->

2021-12-26 09:25 UTC, maty21 commented
___
*[src/components/common/Addon.react.js, line 7 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-Mrq2bElDZKiN2FjHLpu:-Mrq2bElDZKiN2FjHLpv:ba5ekzw) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/components/common/Addon.react.js#L7)):*
> ```JavaScript
> const selectWidth = { width: 90 };
> 
> const Addon = ({ state, options, callback, isDisabled }) =>
> ```

change SignInputAddOn


<!-- Sent from Reviewable.io -->

2021-12-26 09:48 UTC, maty21 commented
___
*[src/components/common/VirtualKeyboard.react.js, line 6 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-Mrq7uzbDbxsIYW9QMzl:-Mrq7uzbDbxsIYW9QMzm:b33wu7o) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/components/common/VirtualKeyboard.react.js#L6)):*
> ```JavaScript
> import _ from 'lodash';
> 
> const VirtualKeyboard = ({
> ```

change name


<!-- Sent from Reviewable.io -->

2021-12-26 10:04 UTC, maty21 commented
___
*[src/hooks/usePipeline.js, line 46 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-MrqBdtz2G9h3cPtsYSb:-MrqBdtz2G9h3cPtsYSc:b-dwt798) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/hooks/usePipeline.js#L46)):*
> ```JavaScript
>         let res = null;
> 
>         if (isEdit) res = await client.put('store/pipelines', { ...data });
> ```

use braces or trinary operator 


<!-- Sent from Reviewable.io -->

2021-12-26 10:06 UTC, maty21 commented
___
*[src/hooks/usePipeline.js, line 41 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-MrqC3rB1az4amoqpOVO:-MrqC3rB1az4amoqpOVP:boyv9y7) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/hooks/usePipeline.js#L41)):*
> ```JavaScript
>   }, []);
> 
>   const addUpdatePipeline = useCallback(
> ```

split to two different hooks one add and one for update 


<!-- Sent from Reviewable.io -->

2021-12-26 10:14 UTC, maty21 commented
___
*[src/Routes/SidebarRight/Bar.js, line 22 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-MrqDx6R-N7Wqjf69whj:-MrqDx6R-N7Wqjf69whk:b-6tsqtj) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/Routes/SidebarRight/Bar.js#L22)):*
> ```JavaScript
> 
> const IconStyleBar = styled(Icon)`
>   font-size: 25px !important;
> ```

 check if must


<!-- Sent from Reviewable.io -->

2021-12-26 10:28 UTC, maty21 commented
___
*[src/Routes/SidebarRight/AddPipeline/Wizard.js, line 135 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-MrqHBx0B4VoD6Hv31Yu:-MrqHBx0B4VoD6Hv31Yv:b2xp0im) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/Routes/SidebarRight/AddPipeline/Wizard.js#L135)):*
> ```JavaScript
>   );
> 
>   const resetKind = useCallback(
> ```

move to hook


<!-- Sent from Reviewable.io -->

2021-12-29 10:04 UTC, maty21 commented
___
*[src/Routes/SidebarRight/AddPipeline/Steps/Nodes/Gateway.js, line 11 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-Ms4dJmF-zlrPoSPcl2f:-Ms4dJmF-zlrPoSPcl2g:bfuv4r0) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/Routes/SidebarRight/AddPipeline/Steps/Nodes/Gateway.js#L11)):*
> ```JavaScript
> import { memoryTypes } from '../../../AddAlgorithm/schema';
> 
> const ctx = React.createContext();
> ```

check if context is needed 


<!-- Sent from Reviewable.io -->

2021-12-29 10:09 UTC, maty21 commented
___
*[src/Routes/SidebarRight/AddPipeline/Steps/Nodes/Output.js, line 13 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-Ms4efgCDPMNYsWhNwwg:-Ms4efgCDPMNYsWhNwwh:b-hfpv33) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/Routes/SidebarRight/AddPipeline/Steps/Nodes/Output.js#L13)):*
> ```JavaScript
> const ctx = React.createContext();
> 
> /** @type {import('../FormUtils').FieldProps} */
> ```

remove


<!-- Sent from Reviewable.io -->

2021-12-29 10:14 UTC, zivglik commented
/deploy cicd

2021-12-29 10:20 UTC, maty21 commented
___
*[src/Routes/SidebarRight/AddPipeline/Steps/Options/index.js, line 67 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-Ms4h9dQ5zlaEENiDp7t:-Ms4h9dR5OklKL5mbpYJ:bucaysp) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/Routes/SidebarRight/AddPipeline/Steps/Options/index.js#L67)):*
> ```JavaScript
>   return (
>     <div style={style}>
>       {isStreamingPipeline !== false && (
> ```

split if possible


<!-- Sent from Reviewable.io -->

2021-12-29 10:24 UTC, maty21 commented
___
*[src/Routes/SidebarRight/MemoryAndStorage/Bars.react.js, line 29 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-Ms4i2v79GeOjZAmMKTj:-Ms4i2v79GeOjZAmMKTk:baa41jt) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/Routes/SidebarRight/MemoryAndStorage/Bars.react.js#L29)):*
> ```JavaScript
>         keys={legend}
>         indexBy="nodes"
>         theme={{
> ```

move it to a prefrencesObject


<!-- Sent from Reviewable.io -->

2021-12-29 10:40 UTC, maty21 commented
___
*[src/Routes/SidebarRight/AddPipeline/Steps/Nodes/InputParseJson/InputField.js, line 10 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-Ms4lceb1ZDksSu5fk--:-Ms4lceb1ZDksSu5fk-0:b-i7nvna) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/Routes/SidebarRight/AddPipeline/Steps/Nodes/InputParseJson/InputField.js#L10)):*
> ```JavaScript
> const SignsOfObjectArray = ['{', '}', '[', ']'];
> 
> function checkInput(input, words) {
> ```

move to helper file and use es6 syntax


<!-- Sent from Reviewable.io -->

2021-12-29 10:42 UTC, maty21 commented
___
*[src/Routes/SidebarRight/AddPipeline/Steps/Nodes/inputKeyValueJson/index.js, line 20 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-Ms4m4Oi1FKxA41SVIqy:-Ms4m4Oi1FKxA41SVIqz:b-hfpv33) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/Routes/SidebarRight/AddPipeline/Steps/Nodes/inputKeyValueJson/index.js#L20)):*
> ```JavaScript
> const emptyEditorStatesKeyValue = ['""', null, 'null', ''];
> 
> // Component [ControllerKeyValue]
> ```

remove


<!-- Sent from Reviewable.io -->

2021-12-29 10:47 UTC, maty21 commented
___
*[src/Routes/SidebarRight/AddPipeline/Steps/Nodes/inputKeyValueJson/index.js, line 33 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-Ms4nD6e-KS7Usx7ZPla:-Ms4nD6e-KS7Usx7ZPlb:b-dcwv91) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/Routes/SidebarRight/AddPipeline/Steps/Nodes/inputKeyValueJson/index.js#L33)):*
> ```JavaScript
>   const [value, setValue] = useState(JSON.stringify(_value));
> 
>   const convertObjectToKeyListKeyValue = useCallback(() => {
> ```

does useCallback needed


<!-- Sent from Reviewable.io -->

2021-12-29 10:55 UTC, maty21 commented
___
*[src/styles/Drawer.styles.js, line 30 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-Ms4p-on1vKOPIEfjL2G:-Ms4p-on1vKOPIEfjL2H:b-rt2hlj) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/styles/Drawer.styles.js#L30)):*
> ```JavaScript
>   z-index: 1000;
> 
>   border-bottom-left-radius: 30px;
> ```

change to 10px


<!-- Sent from Reviewable.io -->

2021-12-29 10:57 UTC, maty21 commented
___
*[src/utils/objects.js, line 1 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-Ms4pOzyCBpcXDrktSWE:-Ms4pOzyCBpcXDrktSWF:bwtqoe0) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/utils/objects.js#L1)):*
> ```JavaScript
> export const tryParseJson = val => {
> ```

change to a more descriptive name for example objectManipulation


<!-- Sent from Reviewable.io -->

2021-12-29 10:58 UTC, maty21 requested changes
> Reviewed 89 of 112 files at r1, 3 of 3 files at r2, 4 of 12 files at r3, 1 of 3 files at r4, 3 of 4 files at r5, 6 of 14 files at r6, 3 of 3 files at r7, 25 of 25 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/176)* status: all files reviewed, 28 unresolved discussions (waiting on @zivglik)

___
*[package.json, line 36 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-MrpvCrM7HToANi6LvDg:-MrpvCrN3iqG-J1mZ3AA:b-8hswxe) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/package.json#L36)):*
> ```JSON
>   },
>   "dependencies": {
>     "@ant-design/compatible": "^1.0.8",
> ```

try remove
___
*[src/index.js, line 10 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-MrpvM7e56rrBQdGT-8b:-MrpvM7fD2WXaT0Ju8N0:bn09smq) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/index.js#L10)):*
> ```JavaScript
> import { init } from 'actions/connection.action';
> import { selectors } from 'reducers';
> import GlobalStyle from './styles/GlobalStyle.styles';
> ```

change back
___
*[src/components/common/FlexBox.react.js, line 8 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-Mrq35exC1jHO8wqX3AK:-Mrq35exC1jHO8wqX3AL:bd0lvpg) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/components/common/FlexBox.react.js#L8)):*
> ```JavaScript
> 
> const FlexAligned = styled(Row)`
>   align-items: ${prop('align', 'center')}!important;
> ```

verify that  important is required
 
___
*[src/components/common/HoverIcon.react.js, line 12 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-Mrq3HKZ5NsCkmdBcL6q:-Mrq3HKZ5NsCkmdBcL6r:b-rymoot) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/components/common/HoverIcon.react.js#L12)):*
> ```JavaScript
>   color: ${COLOR_LAYOUT.darkBorder};
>   :hover {
>     color: ${props => (props.theme.isDarkMode ? '#ffffff' : '#black')};
> ```

see dark comment
___
*[src/components/common/index.js, line 21 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-Mrq5h9N6V6Sf9idKHMd:-Mrq5h9N6V6Sf9idKHMe:b-7dm01i) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/components/common/index.js#L21)):*
> ```JavaScript
> export { default as Tabs } from 'components/common/Tabs/Tabs.react';
> export { default as ErrorBoundary } from 'components/ErrorBoundary';
> export { default as VirtualKeyboard } from 'components/common/VirtualKeyboard.react';
> ```

Change to SignsBoard
___
*[src/hooks/useSiteDarkMode.react.js, line 64 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-MrqCnu9Ep-i4qlTzBh6:-MrqCnu9Ep-i4qlTzBh7:b-j5kna6) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/hooks/useSiteDarkMode.react.js#L64)):*
> ```JavaScript
> };
> 
> export default createStore(useSiteDarkMode);
> ```

check why its needed
___
*[src/Routes/SidebarRight/AddDataSource/index.js, line 168 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-MrqG6Tk8vleSfzdbFHW:-MrqG6Tk8vleSfzdbFHX:bs98h77) ([raw file](https://github.com/kube-hpc/simulator/blob/8ef77f6a16381a4741e0b4843949cdc7052dd252/src/Routes/SidebarRight/AddDataSource/index.js#L168)):*
> ```JavaScript
>   );
> };
> AddDataSource.propTypes = {
> ```

verify that theres is no propTypes
___
*[src/Routes/SidebarRight/AddPipeline/index.js, line 52 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-MrqGsn041RU8VYitDZ4:-MrqGsn17NRcebzOnulr:bivpqlk) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/Routes/SidebarRight/AddPipeline/index.js#L52)):*
> ```JavaScript
> 
>   useEffect(() => {
>     // avoid infinite looping
> ```

move to  hook
___
*[src/styles/index.js, line 13 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-Ms4pDTF2fh3aURPsDr6:-Ms4pDTG-_OkOL9A0UoU:b-ey9pxx) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/styles/index.js#L13)):*
> ```JavaScript
> } from './colors';
> export { default as Display } from './Display.styles';
> // export { default as GlobalStyle } from './GlobalStyle.styles';
> ```

remove comments
___
*[src/utils/string.js, line 1 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-Ms4pfY42ozPvVwIQ8wv:-Ms4pfY42ozPvVwIQ8ww:b-7l67gv) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/utils/string.js#L1)):*
> ```JavaScript
> export const stringify = obj => JSON.stringify(obj, null, 4);
> ```

change to a more descriptive name


<!-- Sent from Reviewable.io -->

2021-12-29 15:01 UTC, zivglik reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/176)* status: all files reviewed, 28 unresolved discussions (waiting on @maty21 and @zivglik)

___
*[package.json, line 36 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-MrpvCrM7HToANi6LvDg:-Ms5JezNDUyhkz7G0uSI:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/package.json#L36)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

try remove
</blockquote></details>

Done.
___
*[src/components/StatusTag.js, line 29 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-Mrq-KgZBwx8a9lzzKBu:-Ms-dhDG2IGGSmliS3QB:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/components/StatusTag.js#L29)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

use theme provider with the following guidelines
 https://css-tricks.com/theming-and-theme-switching-with-react-and-styled-components/
</blockquote></details>

Done.
___
*[src/components/common/Addon.react.js, line 7 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-Mrq2bElDZKiN2FjHLpu:-Ms-eDlLDjXgDIGXcs5a:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/components/common/Addon.react.js#L7)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

change SignInputAddOn
</blockquote></details>

Done.
___
*[src/components/common/FlexBox.react.js, line 8 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-Mrq35exC1jHO8wqX3AK:-Ms5Rds30lQBEkMrpqPL:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/components/common/FlexBox.react.js#L8)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

verify that  important is required
 
</blockquote></details>

Done.



_Code quote:_
```JavaScript
flex-direction: ${prop('direction', 'row')}!important;
```
___
*[src/components/common/HoverIcon.react.js, line 12 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-Mrq3HKZ5NsCkmdBcL6q:-Ms5Ror0AqsqinRymhYr:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/components/common/HoverIcon.react.js#L12)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

see dark comment
</blockquote></details>

Done.
___
*[src/components/common/index.js, line 21 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-Mrq5h9N6V6Sf9idKHMd:-Ms5RsrgE6ThQWRsL8t5:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/components/common/index.js#L21)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

Change to SignsBoard
</blockquote></details>

Done.
___
*[src/components/common/VirtualKeyboard.react.js, line 6 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-Mrq7uzbDbxsIYW9QMzl:-Ms-gD0F4KoH8JiGUqg8:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/components/common/VirtualKeyboard.react.js#L6)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

change name
</blockquote></details>

Done.
___
*[src/hooks/usePipeline.js, line 41 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-MrqC3rB1az4amoqpOVO:-Ms-gMw-CErfSmyiB2l4:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/hooks/usePipeline.js#L41)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

split to two different hooks one add and one for update 
</blockquote></details>

Done.
___
*[src/hooks/usePipeline.js, line 46 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-MrqBdtz2G9h3cPtsYSb:-Ms-gQ1c4gU97X5a78qq:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/hooks/usePipeline.js#L46)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

use braces or trinary operator 
</blockquote></details>

Done.
___
*[src/Routes/SidebarRight/Bar.js, line 22 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-MrqDx6R-N7Wqjf69whj:-Ms-xa7372gb9LrJldf6:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/Routes/SidebarRight/Bar.js#L22)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

 check if must
</blockquote></details>

Done.
___
*[src/Routes/SidebarRight/AddPipeline/index.js, line 52 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-MrqGsn041RU8VYitDZ4:-Ms5TyAq4L-Q0OS9JAPv:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/Routes/SidebarRight/AddPipeline/index.js#L52)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

move to  hook
</blockquote></details>

Done.
___
*[src/Routes/SidebarRight/AddPipeline/Wizard.js, line 135 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-MrqHBx0B4VoD6Hv31Yu:-Ms0AnkR01RwefB57C6T:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/Routes/SidebarRight/AddPipeline/Wizard.js#L135)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

move to hook
</blockquote></details>

Done.
___
*[src/Routes/SidebarRight/AddPipeline/Steps/Nodes/Gateway.js, line 11 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-Ms4dJmF-zlrPoSPcl2f:-Ms5YC7z365ckNNmGU1q:b-33qjw3) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/Routes/SidebarRight/AddPipeline/Steps/Nodes/Gateway.js#L11)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

check if context is needed 
</blockquote></details>

We need it
There is some method to automatically thread the name of the field so that it is set in JSON under a certain common path
___
*[src/Routes/SidebarRight/AddPipeline/Steps/Nodes/Output.js, line 11 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-Ms4eaOG7r_2VeeNNNzw:-Ms5YjIkC3V1RPC-xJpU:b-33qjw3) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/Routes/SidebarRight/AddPipeline/Steps/Nodes/Output.js#L11)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

check if needed
</blockquote></details>

We need it
There is some method to automatically thread the name of the field so that it is set in JSON under a certain common path
___
*[src/Routes/SidebarRight/AddPipeline/Steps/Nodes/Output.js, line 13 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-Ms4efgCDPMNYsWhNwwg:-Ms5YnJP7V3TNJFNuvev:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/Routes/SidebarRight/AddPipeline/Steps/Nodes/Output.js#L13)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[src/Routes/SidebarRight/AddPipeline/Steps/Nodes/inputKeyValueJson/index.js, line 20 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-Ms4m4Oi1FKxA41SVIqy:-Ms5Z4VdCc_eV5X-9svH:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/Routes/SidebarRight/AddPipeline/Steps/Nodes/inputKeyValueJson/index.js#L20)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[src/Routes/SidebarRight/MemoryAndStorage/Bars.react.js, line 29 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-Ms4i2v79GeOjZAmMKTj:-Ms5em8OC6JSKWXM7jDh:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d11 [...]

2021-12-29 16:21 UTC, zivglik reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/176)* status: all files reviewed, 28 unresolved discussions (waiting on @maty21 and @zivglik)

___
*[src/Routes/SidebarRight/AddPipeline/Steps/Nodes/InputParseJson/InputField.js, line 10 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-Ms4lceb1ZDksSu5fk--:-Ms5zgEi9s0iOm0OkS0g:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/Routes/SidebarRight/AddPipeline/Steps/Nodes/InputParseJson/InputField.js#L10)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

move to helper file and use es6 syntax
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-02 09:36 UTC, zivglik reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/176)* status: all files reviewed, 28 unresolved discussions (waiting on @maty21)

___
*[src/index.js, line 10 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-MrpvM7e56rrBQdGT-8b:-MsP8OAx7tNTXrMaXsnd:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/index.js#L10)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

change back
</blockquote></details>

Done.
___
*[src/components/StatusTag.js, line 16 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-Mrpxs3jA2S8cxYtpCcY:-MsOWofj6HHQMSnk7Xdi:b-892286) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/components/StatusTag.js#L16)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

why using this hook u call reusable createStore each time 
</blockquote></details>

We need it
It improves our performance in the face of it and it does not have to be re-rendered every time
We use this occasionally in our HOOKS

Reusable is a solution for state management, based on React Hooks. 
It allows you to transform your custom hooks to singleton stores, 
and subscribe to them directly from any component.

You can read the benefits of this further at the following link
https://www.npmjs.com/package/reusable
___
*[src/hooks/useSiteDarkMode.react.js, line 64 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-MrqCnu9Ep-i4qlTzBh6:-MsOcUjW3Jaeh5Zl2Txa:bcsvr7a) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/hooks/useSiteDarkMode.react.js#L64)):*
> We need it
> It improves our performance in the face of it and it does not have to be re-rendered every time
> We use this occasionally in our HOOKS
> 
> Reusable is a solution for state management, based on React Hooks. 
> It allows you to transform your custom hooks to singleton stores, 
> and subscribe to them directly from any component.
> 
> You can read the benefits of this further at the following link
> https://www.npmjs.com/package/reusable
___
*[src/Routes/SidebarRight/AddDataSource/index.js, line 168 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-MrqG6Tk8vleSfzdbFHW:-MsOdSbH-JbSS-3gZ8bd:b-q7a9m5) ([raw file](https://github.com/kube-hpc/simulator/blob/8ef77f6a16381a4741e0b4843949cdc7052dd252/src/Routes/SidebarRight/AddDataSource/index.js#L168)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

verify that theres is no propTypes
</blockquote></details>


It is a convention that is repeated in our code in several places so that
 in the end it will be possible to address the component in this way

import AddAlgorithm from './AddAlgorithm'; ===> is go to index.js in this folder
import AddPipeline from './AddPipeline'; ===> is go to index.js in this folder
import AddDataSource from './AddDataSource'; ===> is go to index.js in this folder



_Code quote:_
```JavaScript
AddDataSource;
```
___
*[src/Routes/SidebarRight/AddPipeline/Steps/Nodes/inputKeyValueJson/index.js, line 33 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-Ms4nD6e-KS7Usx7ZPla:-MsOen2sEaZVjk801CJ4:ba5hk29) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/Routes/SidebarRight/AddPipeline/Steps/Nodes/inputKeyValueJson/index.js#L33)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

does useCallback needed
</blockquote></details>

You're right there is no advantage to this in this situation
I downloaded it from the code
___
*[src/Routes/SidebarRight/AddPipeline/Steps/Options/index.js, line 67 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-Ms4h9dQ5zlaEENiDp7t:-Ms63XdF6CKJdCVxeis4:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/Routes/SidebarRight/AddPipeline/Steps/Options/index.js#L67)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

split if possible
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-02 09:45 UTC, zivglik commented
/deploy cicd

2022-01-12 09:28 UTC, maty21 commented
___
*[src/components/StatusTag.js, line 10 at r10](https://reviewable.io/reviews/kube-hpc/simulator/176#-MtCbSpF4cD71ODu1WCT:-MtCbSpF4cD71ODu1WCU:b-w4s0mh) ([raw file](https://github.com/kube-hpc/simulator/blob/a681e4d65250f919b973d0d6b66751918e5dcaad/src/components/StatusTag.js#L10)):*
> ```JavaScript
> 
> const TagTheme = styled(Tag)`
>   color: ${props => props.textColor};
> ```

add this to the dark syle


<!-- Sent from Reviewable.io -->

2022-01-12 09:44 UTC, maty21 commented
___
*[src/components/common/Json/JsonEditor/index.js, line 5 at r10](https://reviewable.io/reviews/kube-hpc/simulator/176#-MtCf1c72Ylkw7qc3rbq:-MtCf1c72Ylkw7qc3rbr:bkob3tl) ([raw file](https://github.com/kube-hpc/simulator/blob/a681e4d65250f919b973d0d6b66751918e5dcaad/src/components/common/Json/JsonEditor/index.js#L5)):*
> ```JavaScript
> import React, { useEffect, useState } from 'react';
> import { AutoSizer } from 'react-virtualized';
> import { useSiteDarkMode } from 'hooks';
> ```

change to use stieTheme


<!-- Sent from Reviewable.io -->

2022-01-12 10:35 UTC, maty21 commented
___
*[src/hooks/useWizard.js, line 134 at r10](https://reviewable.io/reviews/kube-hpc/simulator/176#-MtCqbCT9eV5Dh2xTac8:-MtCqbCT9eV5Dh2xTac9:b-svxy1v) ([raw file](https://github.com/kube-hpc/simulator/blob/a681e4d65250f919b973d0d6b66751918e5dcaad/src/hooks/useWizard.js#L134)):*
> ```JavaScript
>   return {
>     steps,
>     setForm,
> ```

component should not be in hook try to see if there is a logic that could stay at hook if so split the file to component and hook


<!-- Sent from Reviewable.io -->

2022-01-12 10:36 UTC, maty21 commented
___
*[src/hooks/useWizardAddPipeline.js, line 5 at r10](https://reviewable.io/reviews/kube-hpc/simulator/176#-MtCr0Vk6un4AbO0UPsj:-MtCr0Vk6un4AbO0UPsk:btwdnoa) ([raw file](https://github.com/kube-hpc/simulator/blob/a681e4d65250f919b973d0d6b66751918e5dcaad/src/hooks/useWizardAddPipeline.js#L5)):*
> ```JavaScript
> import { addPipelineTemplate } from 'config';
> import cleanDeep from 'clean-deep';
> import { usePipeline } from 'hooks';
> ```

same as the wizard hook


<!-- Sent from Reviewable.io -->

2022-01-12 10:47 UTC, maty21 commented
___
*[src/Routes/SidebarRight/MemoryAndStorage/useBars.js, line 2 at r10](https://reviewable.io/reviews/kube-hpc/simulator/176#-MtCtOalCno7NiXmpx8D:-MtCtOalCno7NiXmpx8E:btow8ol) ([raw file](https://github.com/kube-hpc/simulator/blob/a681e4d65250f919b973d0d6b66751918e5dcaad/src/Routes/SidebarRight/MemoryAndStorage/useBars.js#L2)):*
> ```JavaScript
> import React from 'react';
> import { Theme } from 'styles/colors';
> ```

change component name from use maybe to setting 


<!-- Sent from Reviewable.io -->

2022-01-12 11:02 UTC, maty21 commented
___
*[src/Routes/Tables/Jobs/JobTypes.js, line 6 at r10](https://reviewable.io/reviews/kube-hpc/simulator/176#-MtCwznd2tEvNpoXI1f7:-MtCwznd2tEvNpoXI1f8:bifw024) ([raw file](https://github.com/kube-hpc/simulator/blob/a681e4d65250f919b973d0d6b66751918e5dcaad/src/Routes/Tables/Jobs/JobTypes.js#L6)):*
> ```JavaScript
> import React from 'react';
> import styled from 'styled-components';
> import { COLOR_PIPELINE_TYPES, COLOR_PIPELINE_TYPES_TEMPLATE } from 'styles';
> ```

same with color and theme


<!-- Sent from Reviewable.io -->

2022-01-12 11:06 UTC, maty21 commented
___
*[src/styles/colors.js, line 14 at r10](https://reviewable.io/reviews/kube-hpc/simulator/176#-MtCxeM46JH7-OsAwx-c:-MtCxeM51NoXNEi6Nj09:b8l9a7u) ([raw file](https://github.com/kube-hpc/simulator/blob/a681e4d65250f919b973d0d6b66751918e5dcaad/src/styles/colors.js#L14)):*
> ```JavaScript
> export const {
>   COLOR,
>   COLOR_PIPELINE_TYPES,
> ```

THEMES_NAMES = {

dark:Dark,
light:Light
}

   THEMES_NAMES[localStorage.getItem('theme')];


<!-- Sent from Reviewable.io -->

2022-01-12 11:08 UTC, maty21 requested changes
> Reviewed 32 of 40 files at r9, 28 of 28 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/176)* status: all files reviewed, 45 unresolved discussions (waiting on @maty21 and @zivglik)

___
*[package.json, line 36 at r10](https://reviewable.io/reviews/kube-hpc/simulator/176#-MtCqFIe5ApMdq7V4uLz:-MtCqFIe5ApMdq7V4uM-:bz2tcqv) ([raw file](https://github.com/kube-hpc/simulator/blob/a681e4d65250f919b973d0d6b66751918e5dcaad/package.json#L36)):*
> ```JSON
>   },
>   "dependencies": {
>     "@ant-design/compatible": "^1.0.8",
> ```

still there
___
*[src/index.js, line 2 at r10](https://reviewable.io/reviews/kube-hpc/simulator/176#-MtCSRfg4GkL1AvCpva2:-MtCSRfg4GkL1AvCpva3:b-o1r5yj) ([raw file](https://github.com/kube-hpc/simulator/blob/a681e4d65250f919b973d0d6b66751918e5dcaad/src/index.js#L2)):*
> ```JavaScript
> import 'core-js/features/array';
> import { ErrorBoundary } from 'components';
> ```

 globalTheme add to this one
___
*[src/index.js, line 10 at r10](https://reviewable.io/reviews/kube-hpc/simulator/176#-MtCSJrcCSG9qhRMDoZ3:-MtCSJrcCSG9qhRMDoZ4:bbynl1o) ([raw file](https://github.com/kube-hpc/simulator/blob/a681e4d65250f919b973d0d6b66751918e5dcaad/src/index.js#L10)):*
> ```JavaScript
> import { init } from 'actions/connection.action';
> import { selectors } from 'reducers';
> import { GlobalStyle } from './components';
> ```

change to globalTheme
___
*[src/components/GlobalThemeStyle.js, line 1 at r10](https://reviewable.io/reviews/kube-hpc/simulator/176#-MtCXsaq6IZ9PDS3gnjP:-MtCXsaq6IZ9PDS3gnjQ:bx9equ8) ([raw file](https://github.com/kube-hpc/simulator/blob/a681e4d65250f919b973d0d6b66751918e5dcaad/src/components/GlobalThemeStyle.js#L1)):*
> ```JavaScript
> import React, { useEffect, Suspense } from 'react';
> ```

add factory to styles that include css import 
___
*[src/components/index.js, line 3 at r10](https://reviewable.io/reviews/kube-hpc/simulator/176#-MtCY1ed8qNem_TaqDM1:-MtCY1ed8qNem_TaqDM2:bn0hgpi) ([raw file](https://github.com/kube-hpc/simulator/blob/a681e4d65250f919b973d0d6b66751918e5dcaad/src/components/index.js#L3)):*
> ```JavaScript
> export { default as ErrorBoundary } from './ErrorBoundary';
> export { default as Table } from './Table';
> export { default as GlobalStyle } from './GlobalThemeStyle';
> ```

change name
___
*[src/components/StatusTag.js, line 13 at r10](https://reviewable.io/reviews/kube-hpc/simulator/176#-MtCYRoYDzFNdQqd7I7g:-MtCYRoYDzFNdQqd7I7h:be41jq1) ([raw file](https://github.com/kube-hpc/simulator/blob/a681e4d65250f919b973d0d6b66751918e5dcaad/src/components/StatusTag.js#L13)):*
> ```JavaScript
>   ${props =>
>     props.theme.isDarkMode
>       ? `border: 1px solid ${props.borderColor}`
> ```

add to the theme
___
*[src/hooks/useSiteDarkMode.react.js, line 1 at r10](https://reviewable.io/reviews/kube-hpc/simulator/176#-MtCfcxN-Xo0IydnmTDJ:-MtCfcxN-Xo0IydnmTDK:b-1lklsm) ([raw file](https://github.com/kube-hpc/simulator/blob/a681e4d65250f919b973d0d6b66751918e5dcaad/src/hooks/useSiteDarkMode.react.js#L1)):*
> ```JavaScript
> import { useCallback, useState, useRef } from 'react';
> ```

try to make it more generic
___
*[src/Routes/SidebarRight/MemoryAndStorage/Bars.react.js, line 44 at r10](https://reviewable.io/reviews/kube-hpc/simulator/176#-MtCt7fb4D9_yTVb0SGk:-MtCt7fb4D9_yTVb0SGl:bk5w8z2) ([raw file](https://github.com/kube-hpc/simulator/blob/a681e4d65250f919b973d0d6b66751918e5dcaad/src/Routes/SidebarRight/MemoryAndStorage/Bars.react.js#L44)):*
> ```JavaScript
>         layout="horizontal"
>         colors={
>           colorScheme !== '' ? Theme.GRAPH_PALETTE : { scheme: colorScheme }
> ```

move to theme
___
*[src/Routes/Tables/Jobs/JobPriority.js, line 4 at r10](https://reviewable.io/reviews/kube-hpc/simulator/176#-MtCwrE6AMJ-ldlX81tx:-MtCwrE74rHJLXGni0JZ:b-ly1729) ([raw file](https://github.com/kube-hpc/simulator/blob/a681e4d65250f919b973d0d6b66751918e5dcaad/src/Routes/Tables/Jobs/JobPriority.js#L4)):*
> ```JavaScript
> import PropTypes from 'prop-types';
> import React from 'react';
> import { COLOR_PRIORITY, COLOR_PRIORITY_TEMPLATE } from 'styles';
> ```

try to add colors so it will be theme specific
___
*[src/Routes/Tables/Jobs/JobTypes.js, line 17 at r10](https://reviewable.io/reviews/kube-hpc/simulator/176#-MtCx3Tp1_LpSczBHWA7:-MtCx3Tp1_LpSczBHWA8:b-bhene5) ([raw file](https://github.com/kube-hpc/simulator/blob/a681e4d65250f919b973d0d6b66751918e5dcaad/src/Routes/Tables/Jobs/JobTypes.js#L17)):*
> ```JavaScript
>   text-transform: capitalize;
>   border: 1px solid
>     ${props => (props.theme.isDarkMode ? props.borderType : 'inherit')};
> ```

remove isdark


<!-- Sent from Reviewable.io -->

2022-01-17 16:07 UTC, zivglik reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/176)* status: all files reviewed, 45 unresolved discussions (waiting on @maty21 and @zivglik)

___
*[src/index.js, line 10 at r10](https://reviewable.io/reviews/kube-hpc/simulator/176#-MtCSJrcCSG9qhRMDoZ3:-MtclTod7KAQ1FmobVQl:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/a681e4d65250f919b973d0d6b66751918e5dcaad/src/index.js#L10)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

change to globalTheme
</blockquote></details>

Done.
___
*[src/components/GlobalThemeStyle.js, line 1 at r10](https://reviewable.io/reviews/kube-hpc/simulator/176#-MtCXsaq6IZ9PDS3gnjP:-Mtcl_1G34hH-csKYhGc:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/a681e4d65250f919b973d0d6b66751918e5dcaad/src/components/GlobalThemeStyle.js#L1)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

add factory to styles that include css import 
</blockquote></details>

Done.
___
*[src/components/index.js, line 3 at r10](https://reviewable.io/reviews/kube-hpc/simulator/176#-MtCY1ed8qNem_TaqDM1:-MtcliXI4pCmhSBvhFuo:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/a681e4d65250f919b973d0d6b66751918e5dcaad/src/components/index.js#L3)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

change name
</blockquote></details>

Done.
___
*[src/components/StatusTag.js, line 10 at r10](https://reviewable.io/reviews/kube-hpc/simulator/176#-MtCbSpF4cD71ODu1WCT:-Mtclv4x7OfjbcJoeB1Q:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/a681e4d65250f919b973d0d6b66751918e5dcaad/src/components/StatusTag.js#L10)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

add this to the dark syle
</blockquote></details>

Done.
___
*[src/components/StatusTag.js, line 13 at r10](https://reviewable.io/reviews/kube-hpc/simulator/176#-MtCYRoYDzFNdQqd7I7g:-MtclvXn-8tXQEp4ayoj:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/a681e4d65250f919b973d0d6b66751918e5dcaad/src/components/StatusTag.js#L13)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

add to the theme
</blockquote></details>

Done.
___
*[src/hooks/useSiteDarkMode.react.js, line 1 at r10](https://reviewable.io/reviews/kube-hpc/simulator/176#-MtCfcxN-Xo0IydnmTDJ:-MtcmFzd5p5_ZD5puLbI:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/a681e4d65250f919b973d0d6b66751918e5dcaad/src/hooks/useSiteDarkMode.react.js#L1)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

try to make it more generic
</blockquote></details>

Done.
___
*[src/Routes/Tables/Jobs/JobPriority.js, line 4 at r10](https://reviewable.io/reviews/kube-hpc/simulator/176#-MtCwrE6AMJ-ldlX81tx:-Mtcmc6O0kF8XCPgO68s:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/a681e4d65250f919b973d0d6b66751918e5dcaad/src/Routes/Tables/Jobs/JobPriority.js#L4)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

try to add colors so it will be theme specific
</blockquote></details>

Done.
___
*[src/Routes/Tables/Jobs/JobTypes.js, line 6 at r10](https://reviewable.io/reviews/kube-hpc/simulator/176#-MtCwznd2tEvNpoXI1f7:-Mtcmdrg9kyJP4c7785P:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/a681e4d65250f919b973d0d6b66751918e5dcaad/src/Routes/Tables/Jobs/JobTypes.js#L6)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

same with color and theme
</blockquote></details>

Done.
___
*[src/Routes/Tables/Jobs/JobTypes.js, line 17 at r10](https://reviewable.io/reviews/kube-hpc/simulator/176#-MtCx3Tp1_LpSczBHWA7:-MtcmfPi7MIctT4-YGq5:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/a681e4d65250f919b973d0d6b66751918e5dcaad/src/Routes/Tables/Jobs/JobTypes.js#L17)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

remove isdark
</blockquote></details>

Done.
___
*[src/styles/colors.js, line 14 at r10](https://reviewable.io/reviews/kube-hpc/simulator/176#-MtCxeM46JH7-OsAwx-c:-Mtcmhka8WjNVLSgvOU5:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/a681e4d65250f919b973d0d6b66751918e5dcaad/src/styles/colors.js#L14)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

THEMES_NAMES = {

dark:Dark,
light:Light
}

   THEMES_NAMES[localStorage.getItem('theme')];
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-18 11:34 UTC, zivglik reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/176)* status: all files reviewed, 45 unresolved discussions (waiting on @maty21 and @zivglik)

___
*[src/index.js, line 2 at r10](https://reviewable.io/reviews/kube-hpc/simulator/176#-MtCSRfg4GkL1AvCpva2:-MtgvNH83dr-zHX4uqFW:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/a681e4d65250f919b973d0d6b66751918e5dcaad/src/index.js#L2)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

 globalTheme add to this one
</blockquote></details>

Done.
___
*[src/components/common/Json/JsonEditor/index.js, line 5 at r10](https://reviewable.io/reviews/kube-hpc/simulator/176#-MtCf1c72Ylkw7qc3rbq:-MtgvUKODctCSGqdG47d:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/a681e4d65250f919b973d0d6b66751918e5dcaad/src/components/common/Json/JsonEditor/index.js#L5)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

change to use stieTheme
</blockquote></details>

Done.
___
*[src/hooks/useWizard.js, line 134 at r10](https://reviewable.io/reviews/kube-hpc/simulator/176#-MtCqbCT9eV5Dh2xTac8:-MtgvYTt9_RCWXA4erWg:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/a681e4d65250f919b973d0d6b66751918e5dcaad/src/hooks/useWizard.js#L134)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

component should not be in hook try to see if there is a logic that could stay at hook if so split the file to component and hook
</blockquote></details>

Done.
___
*[src/hooks/useWizardAddPipeline.js, line 5 at r10](https://reviewable.io/reviews/kube-hpc/simulator/176#-MtCr0Vk6un4AbO0UPsj:-MtgvZQW6XOndACPuEF7:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/a681e4d65250f919b973d0d6b66751918e5dcaad/src/hooks/useWizardAddPipeline.js#L5)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

same as the wizard hook
</blockquote></details>

Done.
___
*[src/Routes/SidebarRight/MemoryAndStorage/Bars.react.js, line 44 at r10](https://reviewable.io/reviews/kube-hpc/simulator/176#-MtCt7fb4D9_yTVb0SGk:-MtgwXSO1WS4tTKKMhKk:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/a681e4d65250f919b973d0d6b66751918e5dcaad/src/Routes/SidebarRight/MemoryAndStorage/Bars.react.js#L44)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

move to theme
</blockquote></details>

Done.



_Code quote:_
```JavaScript
== '' ? Theme.GRAPH_PALETTE : { scheme: colorScheme }
```
___
*[src/Routes/SidebarRight/MemoryAndStorage/useBars.js, line 2 at r10](https://reviewable.io/reviews/kube-hpc/simulator/176#-MtCtOalCno7NiXmpx8D:-MtgxyHd8BdrFyax0RoT:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/a681e4d65250f919b973d0d6b66751918e5dcaad/src/Routes/SidebarRight/MemoryAndStorage/useBars.js#L2)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

change component name from use maybe to setting 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-19 10:29 UTC, zivglik reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/176)* status: all files reviewed, 45 unresolved discussions (waiting on @maty21)

___
*[package.json, line 36 at r10](https://reviewable.io/reviews/kube-hpc/simulator/176#-MtCqFIe5ApMdq7V4uLz:-MthHWpu2cSyWAG0M20X:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/a681e4d65250f919b973d0d6b66751918e5dcaad/package.json#L36)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

still there
</blockquote></details>

Done.



_Code quote:_
```JSON
"@ant-design/compatible": "^1.0.8"
```


<!-- Sent from Reviewable.io -->

2022-01-19 10:31 UTC, zivglik commented
/deploy cicd

2022-01-23 10:03 UTC, maty21 commented
___
*[src/components/common/HoverIcon.react.js, line 12 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-Mrq3HKZ5NsCkmdBcL6q:-Mu5O-Pt1HGYqgvvDKrZ:b-90maa9) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/components/common/HoverIcon.react.js#L12)):*
<details><summary><i>Previously, zivglik wrote…</i></summary><blockquote>

Done.
</blockquote></details>

change name for component and style to iconstyle



_Code quote:_
```JavaScript
kHover
```


<!-- Sent from Reviewable.io -->

2022-01-23 10:12 UTC, maty21 commented
___
*[src/Routes/Base/LoadingScreen/index.js, line 11 at r12](https://reviewable.io/reviews/kube-hpc/simulator/176#-Mu5Q1ZL22N_8w6vRynG:-Mu5Q1ZL22N_8w6vRynH:b-n9tkj9) ([raw file](https://github.com/kube-hpc/simulator/blob/2d18ea22a8e76aefb1eb772a5a45b5729252169f/src/Routes/Base/LoadingScreen/index.js#L11)):*
> ```JavaScript
> import { useSiteThemeMode } from 'hooks';
> 
> const TitleDark = styled.div`
> ```

change 


<!-- Sent from Reviewable.io -->

2022-01-23 10:14 UTC, maty21 commented
___
*[src/Routes/Base/LoadingScreen/index.js, line 11 at r12](https://reviewable.io/reviews/kube-hpc/simulator/176#-Mu5QQf65PNrkkD_MOG9:-Mu5QQf65PNrkkD_MOGA:bk5kj12) ([raw file](https://github.com/kube-hpc/simulator/blob/2d18ea22a8e76aefb1eb772a5a45b5729252169f/src/Routes/Base/LoadingScreen/index.js#L11)):*
> ```JavaScript
> import { useSiteThemeMode } from 'hooks';
> 
> const TitleDark = styled.div`
> ```

move to style


<!-- Sent from Reviewable.io -->

2022-01-23 10:40 UTC, zivglik reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/176)* status: 100 of 165 files reviewed, 47 unresolved discussions (waiting on @maty21)

___
*[src/components/common/HoverIcon.react.js, line 12 at r8](https://reviewable.io/reviews/kube-hpc/simulator/176#-Mrq3HKZ5NsCkmdBcL6q:-Mu5WN6J-fFJSnUvZQUY:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/441cd16df1ce16d117d962174ba57765e3cc46e6/src/components/common/HoverIcon.react.js#L12)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

change name for component and style to iconstyle
</blockquote></details>

Done.
___
*[src/Routes/Base/LoadingScreen/index.js, line 11 at r12](https://reviewable.io/reviews/kube-hpc/simulator/176#-Mu5Q1ZL22N_8w6vRynG:-Mu5WS1V6Y0FXpv_WE1F:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/2d18ea22a8e76aefb1eb772a5a45b5729252169f/src/Routes/Base/LoadingScreen/index.js#L11)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

change 
</blockquote></details>

Done.
___
*[src/Routes/Base/LoadingScreen/index.js, line 11 at r12](https://reviewable.io/reviews/kube-hpc/simulator/176#-Mu5QQf65PNrkkD_MOG9:-Mu5WSP-A3jjNWWsizcR:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/2d18ea22a8e76aefb1eb772a5a45b5729252169f/src/Routes/Base/LoadingScreen/index.js#L11)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

move to style
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-15 13:21 UTC, zivglik commented
/deploy cicd

2022-02-15 14:03 UTC, yehiyam commented
/deploy test

2022-02-16 08:55 UTC, yehiyam commented
/deploy test

2022-02-16 15:11 UTC, maty21 reviewed
> Reviewed 37 of 55 files at r11, 5 of 6 files at r12.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/176)* status: 124 of 165 files reviewed, 44 unresolved discussions (waiting on @maty21)



<!-- Sent from Reviewable.io -->

2022-02-16 15:11 UTC, maty21 reviewed
> Reviewed 13 of 55 files at r11, 11 of 12 files at r13, 5 of 5 files at r14, 2 of 2 files at r15, 4 of 5 files at r16, 6 of 6 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/176)* status: all files reviewed, 44 unresolved discussions (waiting on @maty21)



<!-- Sent from Reviewable.io -->

2022-02-16 15:18 UTC, maty21 approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/176)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zivglik)



<!-- Sent from Reviewable.io -->

2022-02-16 15:18 UTC, merged